---
# Example on specifying a variable which is not defined at all in the playbooks.
# In this case, `build_id` is a variable that's only introduced when the playbook is called from CLI.
# It is not defined anywhere within var files or the playbooks.
# Usage:
# 1. Without `--build_id`
# ansible-playbook -i <hostname>, block_with_when.yml 
# 2. With `--build_id`
# ansible-playbook -i <hostname>, block_with_when.yml --extra-vars="build_id=100"

- name: Enabling extra variables on command line with `--extra-vars`
  hosts: montypython
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: "Stop XINETD if BUILD_ID is not defined"
      block:
        - debug:
            msg: "Check if BUILD_ID is NOT defined"
        - name: "Stop Xinetd systemd service"
          systemd:
            name: xinetd.service
            state: stopped
      when: build_id is not defined

    - name: "Testing is BUILD_ID is defined"
      block:
        - debug:
            msg: "Check if BUILD_ID is defined"
        - name: "Start Xinetd systemd service"
          systemd:
            name: xinetd.service
            state: started
      when: build_id is defined
...
